server:
  port: 8080
  servlet:
    context-path: /ss
spring:
  datasource:
    url: jdbc:mysql://cdb-fj96zrqa.cd.tencentcdb.com:10062/spring_boot_study?characterEncoding=utf-8
    username: root
    password: root!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
